DanoneRewards/Models/Consumer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanoneRewards.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(ConsumerMetadata))]
    public partial class Consumer
    {
        public Consumer()
        {
            this.ConsumerForgetPasswords = new HashSet<ConsumerForgetPassword>();
            this.Coupons = new HashSet<Coupon>();
            this.Rewards = new HashSet<Reward>();
        }
    
        public int ConsumerId { get; set; }
        public string Name { get; set; }
        public string ChildName { get; set; }
        public int ChildAge { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string DoctorName { get; set; }
        public string DoctorArea { get; set; }
        public string DoctorCity { get; set; }
        public string DoctorAddress { get; set; }
        public string StoreName { get; set; }
        public string FbId { get; set; }
        public string FbToken { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string MobileNumber { get; set; }
    
        public virtual ICollection<ConsumerForgetPassword> ConsumerForgetPasswords { get; set; }
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual ICollection<Reward> Rewards { get; set; }
    }
}

DanoneRewards/Controllers/ConsumersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DanoneRewards.Models;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using DanoneRewards.Utilities;
using DanoneRewards.ViewModels;
using PagedList;
using DanoneRewards.Content.MyResources;
namespace DanoneRewards.Controllers
{
    public class ConsumersController : BaseController
    {
        private DanoneRewardsEntities db = new DanoneRewardsEntities();
        // GET: Consumers
        [CustomAuthorize(Roles = "AdminUser")]
        public ActionResult Index(string SortOrder, string City, string Area, string CouponNum, string currentFilter, string searchString, int? page)
        {
            var ConsumersLst = from s in db.Consumers select s;
            ConsumersLst = ConsumersLst.Include(s => s.Coupons);
            var NumberOfConsumers  = ConsumersLst.Count();
            TempData["NumberOfConsumers"] = NumberOfConsumers;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            City = string.IsNullOrEmpty(City) ? TempData.Peek("CityFilter") == null ? "" : TempData["CityFilter"].ToString() : City;
            if (!string.IsNullOrEmpty(City))
            {
                ConsumersLst = ConsumersLst.Where(s => s.City.Equals(City));
            }
            TempData["CityFilter"] = City;

            Area = string.IsNullOrEmpty(Area) ? TempData.Peek("AreaFilter") == null ? "" : TempData["AreaFilter"].ToString() : Area;
            if (!string.IsNullOrEmpty(Area))
            {
                ConsumersLst = ConsumersLst.Where(s => s.Area.Equals(Area));
            }
            TempData["AreaFilter"] = Area;

            CouponNum = string.IsNullOrEmpty(CouponNum) ? TempData.Peek("CouponNumFilter") == null ? "" : TempData["CouponNumFilter"].ToString() : CouponNum;
            if (!string.IsNullOrEmpty(CouponNum))
            {
                int CouponsCount = int.Parse(CouponNum);
                ConsumersLst = ConsumersLst.Where(c => c.Coupons.Count > CouponsCount);
            }
            TempData["CouponNumFilter"] = CouponNum;


            if (string.IsNullOrEmpty(SortOrder) && TempData.Peek("RegisteredSortOrder") == null)
            {
                SortOrder = "Name";
                ViewBag.NameSortParm = "Name";
                ViewBag.ChildNameSortParm = "ChildName";
                ViewBag.ChildAgeSortParm = "ChildAge";
                ViewBag.AreaSortParm = "Area";
                ViewBag.CitySortParm = "City";
                ViewBag.DoctorNameSortParm = "DoctorName";
                ViewBag.StoreNameSortParm = "StoreName";
                ViewBag.CouponNumSortParm = "CouponNum";
            }
            else if (string.IsNullOrEmpty(SortOrder) && TempData.Peek("RegisteredSortOrder") != null)
            {
                SortOrder = TempData.Peek("RegisteredSortOrder").ToString();
                ViewBag.NameSortParm = "Name";
                ViewBag.ChildNameSortParm = "ChildName";
                ViewBag.ChildAgeSortParm = "ChildAge";
                ViewBag.AreaSortParm = "Area";
                ViewBag.CitySortParm = "City";
                ViewBag.DoctorNameSortParm = "DoctorName";
                ViewBag.StoreNameSortParm = "StoreName";
                ViewBag.CouponNumSortParm = "CouponNum";
            }
            else
            {
                ViewBag.NameSortParm = SortOrder == "Name" ? "Name_desc" : "Name";
                ViewBag.ChildNameSortParm = SortOrder == "ChildName" ? "ChildName_desc" : "ChildName";
                ViewBag.ChildAgeSortParm = SortOrder == "ChildAge" ? "ChildAge_desc" : "ChildAge";
                ViewBag.AreaSortParm = SortOrder == "Area" ? "Area_desc" : "Area";
                ViewBag.CitySortParm = SortOrder == "City" ? "City_desc" : "City";
                ViewBag.DoctorNameSortParm = SortOrder == "DoctorName" ? "DoctorName_desc" : "DoctorName";
                ViewBag.StoreNameSortParm = SortOrder == "StoreName" ? "StoreName_desc" : "StoreName";
                ViewBag.CouponNumSortParm = SortOrder == "CouponNum" ? "CouponNum_desc" : "CouponNum";
            }
            switch (SortOrder)
            {
                case "Name":
                    ConsumersLst = ConsumersLst.OrderBy(s => s.Name);
                    break;
                case "Name_desc":
                    ConsumersLst = ConsumersLst.OrderByDescending(s => s.Name);
                    break;
                case "ChildName":
                    ConsumersLst = ConsumersLst.OrderBy(s => s.ChildName);
                    break;
                case "ChildName_desc":
                    ConsumersLst = ConsumersLst.OrderByDescending(s => s.ChildName);
                    break;
                case "ChildAge":
                    ConsumersLst = ConsumersLst.OrderBy(s => s.ChildAge);
                    break;
                case "ChildAge_desc":
                    ConsumersLst = ConsumersLst.OrderByDescending(s => s.ChildAge);
                    break;
                case "Area":
                    ConsumersLst = ConsumersLst.OrderBy(s => s.Area);
                    break;
                case "Area_desc":
                    ConsumersLst = ConsumersLst.OrderByDescending(s => s.Area);
                    break;
                case "City":
                    ConsumersLst = ConsumersLst.OrderBy(s => s.City);
                    break;
                case "City_desc":
                    ConsumersLst = ConsumersLst.OrderByDescending(s => s.City);
                    break;
                case "DoctorName":
                    ConsumersLst = ConsumersLst.OrderBy(s => s.DoctorName);
                    break;
                case "DoctorName_desc":
                    ConsumersLst = ConsumersLst.OrderByDescending(s => s.DoctorName);
                    break;
                case "StoreName":
                    ConsumersLst = ConsumersLst.OrderBy(s => s.StoreName);
                    break;
                case "StoreName_desc":
                    ConsumersLst = ConsumersLst.OrderByDescending(s => s.StoreName);
                    break;
                case "CouponNum":
                    ConsumersLst = ConsumersLst.OrderBy(s => s.Coupons.Count);
                    break;
                case "CouponNum_desc":
                    ConsumersLst = ConsumersLst.OrderByDescending(s => s.Coupons.Count);
                    break;
            }
            int PageNumber = (page ?? 1);
            var Result = ConsumersLst.Select(c => new RegisteredConsumers { ConsumerModel = c, CouponsNum = c.Coupons.Count }).ToPagedList(PageNumber, int.Parse(System.Configuration.ConfigurationManager.AppSettings["PageSize"]));
            var ResultList = ConsumersLst.Select(c => new RegisteredConsumers { ConsumerModel = c, CouponsNum = c.Coupons.Count }).ToList();
            TempData["RegisteredSortOrder"] = SortOrder;
            TempData["RegisteredConsumersTemp"] = ResultList;
            TempData["ConsumersTemp"] = ConsumersLst;
            return View(Result);

        }



        // GET: Consumers/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Consumer consumer = db.Consumers.Find(id);
        //    if (consumer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(consumer);
        //}



        // GET: Consumers/Create
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpGet]
        public ActionResult RegisterPage()
        {
            return View("RegisterPage");
        }


        public ActionResult LoginPage()
        {
            return View("LoginPage");
        }
        public void loginFunc(string username, string password, bool Ispresistent = true)
        {
            var ident = new ClaimsIdentity(
              new[] { 
              new Claim(ClaimTypes.NameIdentifier, username),
              new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider", "ASP.NET Identity", "http://www.w3.org/2001/XMLSchema#string"),
              new Claim(ClaimTypes.Name,username),
              new Claim(ClaimTypes.Role, "Registered")

          },
              DefaultAuthenticationTypes.ApplicationCookie);

            HttpContext.GetOwinContext().Authentication.SignIn(
           new AuthenticationProperties { IsPersistent = false, ExpiresUtc = DateTime.Now.AddYears(1) }, ident);
        }
        [HttpPost]
        public ActionResult Login(ConsumerLoginRegister model)
        {
            if (TryValidateModel(model.ObjLoginViewModel))
            {
                string username = model.ObjLoginViewModel.Email;
                string password = SecurityManager.GetMD5Password(model.ObjLoginViewModel.Password);
                bool rememberMe = model.ObjLoginViewModel.RememberMe;
                if (new UserManager().IsValid(username, password))
                {
                    loginFunc(username, password, rememberMe);
                    if (TempData.Peek("CouponKey") != null && TempData.Peek("CouponKey").ToString() != "")
                    {
                        var CouponId = int.Parse(TempData.Peek("CouponKey").ToString());
                        var ObjCoupon = db.Coupons.Where(x => x.CouponId == CouponId).FirstOrDefault();
                        if (ObjCoupon.RedeemedBy != null)
                            return RedirectToAction("Index", "Home");

DanoneRewards/Views/Consumers/Delete.cshtml
@model DanoneRewards.Models.Consumer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Consumer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChildName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChildName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChildAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChildAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorArea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorArea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FbId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FbId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FbToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FbToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DanoneRewards/Views/Consumers/Details.cshtml
@model DanoneRewards.Models.Consumer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Consumer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChildName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChildName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChildAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChildAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorArea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorArea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FbId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FbId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FbToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FbToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ConsumerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DanoneRewards/Views/Consumers/LoginPage.cshtml
@using DanoneRewards.Models
@model ConsumerLoginRegister
@{
    ViewBag.Title = "LoginPage";
}
@section Scripts {
    @Scripts.Render("~/Scripts/FacebookScript.js")
}
<div class="content-bg fs-30 col-xs-12">
    <div class="degp-badge">
        <img src="/Content/img/badge.png" class="visible-lg visible-md" />
        <img src="/Content/img/badgesmall.png" class="visible-xs visible-sm" />
    </div>
    <div class="row">
        <div>
            <section id=" loginform">
                @using (Html.BeginForm("Login", "Consumers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="clearfix h50 visible-xs visible-md visible-lg">
                    </div>
                    <div class="clearfix h30 visible-sm">
                    </div>
                    <h1 class="fs-25">@Resource.Login</h1>
                    <div class="clearfix h10">
                    </div>
                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1">
                            @Html.TextBoxFor(m => m.ObjLoginViewModel.Email, new { placeholder = @Resource.Email, @class = "brandedtext" })
                            @Html.ValidationMessageFor(m => m.ObjLoginViewModel.Email, "", new { @class = "text-danger" })
                    </div>
                    </div>
                    <div class="clearfix h10">
                    </div>
                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1">
                            @Html.PasswordFor(m => m.ObjLoginViewModel.Password, new { placeholder = @Resource.Password, @class = "brandedtext" })
                            @Html.ValidationMessageFor(m => m.ObjLoginViewModel.Password, "", new { @class = "text-danger" })
                            @if (TempData["LoginError"] != null && TempData["LoginError"].ToString() == "LoginError")
                            {
                                <div class="clearfix h10">
                                </div>
                                <div class="bad-login" style="">@Resource.InvalidUserName</div>
                            }
                        </div>
                    </div>
                    <div class="clearfix h10">
                    </div>
                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1 visible-md visible-lg fs-20 login-link">
                            @Html.ActionLink(Resource.ForgotPassword, "Create", "ConsumerForgetPasswords")
                        </div>
                        <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1 fs-16 visible-xs login-link">
                            @Html.ActionLink("Forgot password? ", "Create", "ConsumerForgetPasswords")
                        </div>
                    </div>
                    <div class="clearfix h10">
                    </div>
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">
                            <input type="submit" value="@Resource.Login" class="login brandedbutton" />
                        </div>
                    </div>
                    <div class="clearfix h10">
                    </div>
                    <div class="row">
                        <div class="or-div-container col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1">
                            <div class="or-div">
                                <h1 class="fs-25">
                                    @Resource.OR
                                </h1>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <a href="#" class="col-xs-12 col-sm-4 col-sm-offset-4" onclick="FBLogin()">
                            <img src="/Content/img/fb-login-thin.png" class="img-responsive margin0auto" style="width:80%;" />
                        </a>
                    </div>
                    <div class="clearfix h30 visible-xs visible-sm">
                    </div>
                }
            </section>
        </div>
    </div>
</div>

DanoneRewards/Views/Consumers/RegisterPage.cshtml
@using DanoneRewards.Models
@model ConsumerLoginRegister
@{
    ViewBag.Title = "RegisterPage";
}
@section Scripts {
    @Scripts.Render("~/Scripts/FacebookScript.js")
}
<div>
    <div class="content-bg">
        <div class="degp-badge">
            <img src="/Content/img/badge.png" class="visible-lg visible-md" />
            <img src="/Content/img/badgesmall.png" class="visible-xs visible-sm" />
        </div>
        @using (Html.BeginForm("ContinueToRegestraion", "Consumers", FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
            @Html.AntiForgeryToken()
            <div class="clearfix h50 visible-xs visible-md visible-lg">
            </div>
            <div class="clearfix h30 visible-sm">
            </div>
            <h1 class="fs-25 inline">@Resource.Register</h1><span class="mandatory fs-40"> *</span>
            <div class="clearfix h15">
            </div>
            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1">
                    @Html.TextBoxFor(m => m.ObjRegisterViewModel.Name, new { placeholder = @Resource.Name, @class = "brandedtext" })
                    @Html.ValidationMessageFor(m => m.ObjRegisterViewModel.Name, "", new { @class = "text-danger" })
                </div>
                @*<div class="col-sm-1 mandatory fs-40 mandatory-field">*</div>*@
            </div>
            <div class="clearfix h15">
            </div>
            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1">
                    @Html.TextBoxFor(m => m.ObjRegisterViewModel.Email, new { placeholder = @Resource.Email, @class = "brandedtext" })
                    @Html.ValidationMessageFor(m => m.ObjRegisterViewModel.Email, "", new { @class = "text-danger" })
                </div>
                @*<div class="col-sm-1 mandatory fs-40 mandatory-field">*</div>*@
            </div>
            <div class="clearfix h15">
            </div> 
            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1">
                    @Html.PasswordFor(m => m.ObjRegisterViewModel.Password, new { placeholder = @Resource.Password, @class = "brandedtext" })
                    @Html.ValidationMessageFor(m => m.ObjRegisterViewModel.Password, "", new { @class = "text-danger" })
                </div>
                @*<div class="col-sm-1 mandatory fs-40 mandatory-field">*</div>*@
            </div>
            <div class="clearfix h15">
            </div> 
            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1">
                    @Html.TextBoxFor(m => m.ObjRegisterViewModel.Mobile, new { placeholder = @Resource.Mobile, @class = "brandedtext" })
                    @Html.ValidationMessageFor(m => m.ObjRegisterViewModel.Mobile, "", new { @class = "text-danger" })
                </div>
                @*<div class="col-sm-1 mandatory fs-40 mandatory-field">*</div>*@
            </div>
            <div class="clearfix h10"></div>
            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1 mandatory-block fs-16">
                    <span class="mandatory">*</span> @Resource.mandatory_indicate
                </div>
            </div>
            <div class="clearfix h10"></div>
            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1">
                    <input type="submit" value="@Resource.Continue" class="register button brandedbutton" />
                </div>
            </div>
            <div class="clearfix h30">
            </div>
        }
    </div>
</div>

DanoneRewards/Views/Consumers/ResetPassword.cshtml
@model DanoneRewards.Models.Consumer

@{
    ViewBag.Title = "ResetPassword";
}

@using (Html.BeginForm("ResetPasswordValidation", "Consumers"))
{
    <div class="form-horizontal whitebg text-center">
        <div class="row">
            <div class="col-xs-12">
                <h2>@Resource.ResetPassword</h2>
            </div>
        </div>
        <div class="clearfix h30">
        </div>
        @if (TempData.Peek("ResetCodeValidation") == null)
        {
            <p class="lead" style="color:darkred">Page Not Found 404</p>
        }
        else if (TempData.Peek("ResetCodeValidation") == "Valid")
        {
            <input class="brandedtext" id="NewPassword" name="NewPassword" required placeholder="@Resource.NewPassword" />
            <div class="clearfix h30">
            </div>
            <input class="brandedtext" id="NewPasswordConfirmation" name="NewPasswordConfirmation" required placeholder="@Resource.NewPasswordConfirm" />
            <div class="clearfix h30">
            </div>
            <input type="submit" name="ResetPasswordBtn brandedbutton" class="brandedbutton sub-code" value="@Resource.ResetPassword" />
        }
        else
            if (TempData.Peek("ResetCodeValidation") == "Expired")
            {
                <p class="lead" style="color:darkred">Expired</p>
            }
            else if (TempData.Peek("ResetCodeValidation") == "404")
            {
                <p class="lead" style="color:darkred">Page Not Found 404</p>
            }
        <div class="clearfix h30">
        </div>
    </div>
}