DanoneRewards/Models/Store.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanoneRewards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Coupons = new HashSet<Coupon>();
        }
    
        public long StoreId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}

DanoneRewards/Controllers/StoresController.cs
using DanoneRewards.Models;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Linq;
using System.Collections.Generic;
using DanoneRewards.Utilities;
using DanoneRewards.Content.MyResources;
using System;
namespace DanoneRewards.Controllers
{
    public class StoresController : Controller
    {
        private DanoneRewardsEntities db = new DanoneRewardsEntities();
        public class StoresMetaViewModel
        {
            [StringLength(19, ErrorMessage = "Enter a valid Voucher Code")]
            [Required(ErrorMessage = "Voucher code is required")]
            public string VoucherCodeField { set; get; }

            [Required(ErrorMessage = "Store code is required")]
            public string StoreCodeField { set; get; }
        }

        [HttpGet]
        public ActionResult SaveStore()
        {
            return View("SaveStore");
        }
        public ActionResult PrintStore()
        {

            return View("PrintStore");

        }

        [HttpPost]
        public ActionResult SaveStore(StoresMetaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var CouponVoucher = model.VoucherCodeField.ToString().Trim();
                var StoreCode = model.StoreCodeField.ToString().Trim();
                long StoreId = 0;
                CouponVoucher = DanoneRewards.Utilities.UtilityHelper.AddCouponDashes(CouponVoucher);
                var StoreObj = db.Stores.AsNoTracking().FirstOrDefault(s => s.Code == StoreCode);
                var CouponObj = db.Coupons.Where(c => c.Voucher == CouponVoucher).FirstOrDefault();
                if (CouponObj != null)
                {
                    var CouponObjRedeemed = CouponObj.RedeemStoreId;
                    if (CouponObjRedeemed != null)
                    {
                        ModelState.AddModelError("", Resource.VoucherUsed);
                        return View();
                    }
                }
                if (StoreObj != null)
                {
                    StoreId = StoreObj.StoreId;
                }
                if (CouponObj != null && StoreObj != null)
                {
                    CouponObj.RedeemStoreId = StoreId;
                    CouponObj.RedeemStoreDate = DateTime.Now;
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception e)
                    {
                        Console.Write(e);
                    }
                    TempData["Refresh"] = "Refresh";
                    TempData["voucherCode"] = CouponVoucher;
                    TempData["storeCode"] = StoreCode;
                    UtilityHelper.SendStoreRedeemedVoucherMail(StoreObj.Name, CouponVoucher, DateTime.Now.ToString("dd/MM/yyyy hh:mm a"));
                    return RedirectToAction("PrintStore");
                }
                else if (CouponObj == null && StoreObj != null)
                {
                    ModelState.AddModelError("", Resource.VoucherNotExist);
                }
                else if (CouponObj != null && StoreObj == null)
                {
                    ModelState.AddModelError("", Resource.StoreNotExist);
                }
                else
                {
                    ModelState.AddModelError("", Resource.StoreAndVoucherNotExist);
                }

                return View();
            }
            else
            {
                return View();
            }

        }

        //public void FillStore()
        //{
        //    Random rnd = new Random();
        //    var lstAddedCodes = new List<string>();
        //    var lstStores = db.Stores.Where(s => s.Code == null).ToList();
        //    if (lstStores != null && lstStores.Count > 0)
        //    {
        //        var CodeNew = "";
        //        foreach (var item in lstStores)
        //        {
        //            CodeNew = GenerateStoreCode(lstAddedCodes);
        //            lstAddedCodes.Add(CodeNew);
        //            item.Code = CodeNew;
        //        }
        //        try
        //        {
        //            db.SaveChanges();
        //        }
        //        catch (Exception e)
        //        {
        //            Console.Write(e);
        //        }
        //    }
        //}

        //private string GenerateStoreCode(List<string> lstAddedCodes)
        //{
        //    var AddedNew = false;
        //    string code = "";
        //    Random rnd = new Random();
        //    while (!AddedNew)
        //    {
        //        code = rnd.Next(1, 10) + "" + rnd.Next(1, 10) + "" + rnd.Next(1, 10) + "" + rnd.Next(1, 10) + "" + rnd.Next(1, 10) + "" + rnd.Next(1, 10);
        //        if (!lstAddedCodes.Contains(code))
        //            AddedNew = true;
        //    }
        //    return code;
        //}
    }
}

DanoneRewards/Views/Stores/PrintStore.cshtml
@{
    ViewBag.Title = "PrintStore";
}

<div class="whitebg padding-20">
    <div id="printable">
        <div class="row">
            <h4 class="fs-40 col-md-12"><span>@Resource.Store</span></h4>
        </div>
        <div class="clearfix h10"></div>
        <div class="row">
            <div class="col-md-2 fs-25 boldtext">
                Voucher code:
            </div>
            <div class="col-md-10 fs-25 boldtext">
                @TempData.Peek("voucherCode")
            </div>
        </div>
        <div class="clearfix h10"></div>
        <div class="row">
            <div class="col-md-2 fs-25 boldtext">
                Store code:
            </div>
            <div class="col-md-10 fs-25 boldtext">
                @TempData.Peek("storeCode")
            </div>
        </div>
        <div class="clearfix h10"></div>
    </div>
    <div class="row">
        <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-default fs-25" onclick="printIt()">Print</button>
            @Html.ActionLink("New Voucher", "SaveStore", null, htmlAttributes: new { @class = "btn btn-default fs-25" })
        </div>
    </div>
</div>
<script type="text/javascript">
    function printIt() {
        var pageContents = $("body").html();
        $("#printable .row").css("margin-left", "15px");
        var pageContents = $("body").html();
        $("body").html($("#printable").html());
        window.print();
        window.close();
        $("body").html(pageContents);
        //var page = window.self;
        //var printPage = window.open("http://localhost:4980/en/Stores/PrintStore");
        //printPage.print();
        //printPage.onafterprint = function () {
        //    printPage.close();
        //}
        //page.history.back();
    }
</script>

DanoneRewards/Views/Stores/SaveStore.cshtml
@model  DanoneRewards.Controllers.StoresController.StoresMetaViewModel
<br />
<br />
<div class="whitebg padding-20">
    @using (Html.BeginForm("SaveStore", "Stores", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger fs-20" })
        <div class="form-group">
            @Html.LabelFor(model => model.VoucherCodeField, "Enter Voucher Code", htmlAttributes: new { @class = "control-label col-md-2 fs-25" })
            <div class="col-md-4">
                @Html.ValidationMessageFor(model => model.VoucherCodeField, "", new { @style = "border-radius: 5px; background-color: rgba(255,192,202,1);color: #000;" })
                @Html.EditorFor(model => model.VoucherCodeField, new { htmlAttributes = new { @class = "form-control fs-25" } })
            </div>
        </div>
        <div class="clearfix h20"></div>
        <div class="form-group">
            @Html.LabelFor(model => model.StoreCodeField, "Enter Store Code", htmlAttributes: new { @class = "control-label col-md-2 fs-25" })
            <div class="col-md-4">
                @Html.ValidationMessageFor(model => model.StoreCodeField, "", new { @style = "border-radius: 5px; background-color: rgba(255,192,202,1);color: #000;" })
                @Html.EditorFor(model => model.StoreCodeField, new { htmlAttributes = new { @class = "form-control fs-25" } })
            </div>
        </div>
        <div class="clearfix h10"></div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default fs-25" />
            </div>
        </div>
    }
</div>