DanoneRewards/Models/Reward.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanoneRewards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int RewardId { get; set; }
        public Nullable<int> ConsumerId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> GenerationDate { get; set; }
    
        public virtual Consumer Consumer { get; set; }
    }
}

DanoneRewards/Controllers/RewardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DanoneRewards.Models;
using DanoneRewards.ViewModels;
using PagedList;

namespace DanoneRewards.Controllers
{
    public class RewardsController : BaseController
    {
        private DanoneRewardsEntities db = new DanoneRewardsEntities();

        // GET: Rewards
        [CustomAuthorize(Roles = "AdminUser")]
        public ActionResult Index(string SortOrder, string currentFilter, string searchString, string Name, int? page)
        {
            var rewardsLst = from s in db.Rewards select s;
            var rewards = db.Rewards.Include(r => r.Consumer);
            var NumberOfRewards = rewardsLst.Count();
            TempData["NumberOfRewards"] = NumberOfRewards;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            if (string.IsNullOrEmpty(Name))
            {
                Name = "";
            }
            else
            {
                Name = string.IsNullOrEmpty(Name) ? TempData["NameFilter"] == null ? "" : TempData["NameFilter"].ToString() : Name;
                rewards = rewards.Where(s => s.Consumer.Name.Contains(Name));
            }

            TempData["NameFilter"] = Name;
            ViewBag.CurrentFilter = searchString;
            if (string.IsNullOrEmpty(SortOrder) && TempData.Peek("RewardSortOrder") == null)
            {
                SortOrder = "Name";
                ViewBag.NameSortParm = "Name";
                ViewBag.MessageSortParm = "Message";
                ViewBag.GenerationDateSortParm = "GenerationDate";
            }
            else if (string.IsNullOrEmpty(SortOrder) && TempData.Peek("RewardSortOrder") != null)
            {
                SortOrder = TempData.Peek("RewardSortOrder").ToString();
                ViewBag.NameSortParm = "Name";
                ViewBag.MessageSortParm = "Message";
                ViewBag.GenerationDateSortParm = "GenerationDate";
            }
            else
            {
                ViewBag.NameSortParm = SortOrder == "Name" ? "Name_desc" : "Name";
                ViewBag.MessageSortParm = SortOrder == "Message" ? "Message_desc" : "Message";
                ViewBag.GenerationDateSortParm = SortOrder == "GenerationDate" ? "GenerationDate_desc" : "GenerationDate";
            }

            switch (SortOrder)
            {
                case "Name":
                    rewards = rewards.OrderBy(r => r.Consumer.Name);
                    break;
                case "Name_desc":
                    rewards = rewards.OrderByDescending(r => r.Consumer.Name);
                    break;
                case "Message":
                    rewards = rewards.OrderBy(r => r.Message);
                    break;
                case "Message_desc":
                    rewards = rewards.OrderByDescending(r => r.Message);
                    break;
                case "GenerationDate":
                    rewards = rewards.OrderBy(r => r.GenerationDate);
                    break;
                case "GenerationDate_desc":
                    rewards = rewards.OrderByDescending(r => r.GenerationDate);
                    break;
            }
            int PageNumber = (page ?? 1);
            TempData["RewardSortOrder"] = SortOrder;
            TempData["RewardsTemp"] = rewards.ToList();
            return View(rewards.ToPagedList(PageNumber, int.Parse(System.Configuration.ConfigurationManager.AppSettings["PageSize"])));
        }
        // GET: Rewards/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Reward reward = db.Rewards.Find(id);
        //    if (reward == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(reward);
        //}

        // GET: Rewards/Create
        //public ActionResult Create()
        //{
        //    ViewBag.ConsumerId = new SelectList(db.Consumers, "ConsumerId", "Name");
        //    return View();
        //}

        // POST: Rewards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "RewardId,ConsumerId,Message,GenerationDate")] Reward reward)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Rewards.Add(reward);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.ConsumerId = new SelectList(db.Consumers, "ConsumerId", "Name", reward.ConsumerId);
        //    return View(reward);
        //}

        // GET: Rewards/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Reward reward = db.Rewards.Find(id);
        //    if (reward == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ConsumerId = new SelectList(db.Consumers, "ConsumerId", "Name", reward.ConsumerId);
        //    return View(reward);
        //}

        // POST: Rewards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "RewardId,ConsumerId,Message,GenerationDate")] Reward reward)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(reward).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ConsumerId = new SelectList(db.Consumers, "ConsumerId", "Name", reward.ConsumerId);
        //    return View(reward);
        //}

        // GET: Rewards/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Reward reward = db.Rewards.Find(id);
        //    if (reward == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(reward);
        //}

        // POST: Rewards/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Reward reward = db.Rewards.Find(id);
        //    db.Rewards.Remove(reward);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [CustomAuthorize(Roles = "AdminUser")]
        public void ExportCsv()
        {
            Consumer currentUser = db.Consumers.Where(x => x.Email == User.Identity.Name.ToString()).FirstOrDefault();
            var Rewards = db.Rewards.Select(r => new { r.Consumer.Name, r.Message, r.GenerationDate }).ToList();
            Utilities.UtilityHelper.ExportToExcel(Rewards, Response, "Danone_Rewards_List");
        }

        [CustomAuthorize(Roles = "AdminUser")]
        public void ExportRwardsCsv()
        {

            List<Reward> tempRwards= (List<Reward>)TempData.Peek("RewardsTemp");
            Utilities.UtilityHelper.ExportToExcel(tempRwards.Select(c => new
            {
                c.Consumer.Name,
                c.Message,
                c.GenerationDate        
            }).ToList(), Response, "Danone_Reward_Coupons");
        }

        [CustomAuthorize(Roles = "AdminUser")]
        public ActionResult DrawReward()
        {

            List<RegisteredConsumers> listCons = (List<RegisteredConsumers>)TempData.Peek("RegisteredConsumersTemp");
            var qry = from row in listCons
                      select row;
            int count = listCons.Count();
            int IndexCons = new Random().Next(count);
            var result = qry.Where((row, index) => index == IndexCons);
            RegisteredConsumers Winner = result.FirstOrDefault();
            TempData["CurrentDrawWinner"] = Winner;
            TempData["CurrentDrawWinnerName"] = Winner.ConsumerModel.Name;
            return RedirectToAction("ContinueDraw");
        }


        [CustomAuthorize(Roles = "AdminUser")]
        public ActionResult ContinueDraw()
        {
            return View();
        }
        [CustomAuthorize(Roles = "AdminUser")]
        public ActionResult ConfirmDraw(string winnerMsg)
        {
            RegisteredConsumers Winner = (RegisteredConsumers)TempData.Peek("CurrentDrawWinner");
            Reward Rwrd = new Reward();
            Rwrd.GenerationDate = DateTime.Now;
            Rwrd.Message = winnerMsg;
            Rwrd.ConsumerId = Winner.ConsumerModel.ConsumerId;
            db.Rewards.Add(Rwrd);
            db.SaveChanges();
            Utilities.UtilityHelper.SendMail(Winner.ConsumerModel.Email, "Danone Rewards Draw", Rwrd.Message);
            return RedirectToAction("Index", "Consumers");
        }


    }
}

DanoneRewards/Views/Rewards/ContinueDraw.cshtml
@model DanoneRewards.Models.Reward
@{
    ViewBag.Title = "ContinueDraw";
}
<div class="clearfix h20"></div>
<div class="whitebg padding-20">
    <h2 class="nomargin">Complete the draw</h2>
    <div class="clearfix h20"></div>
    @using (Html.BeginForm("ConfirmDraw", "Rewards"))
    {
        <p class="fs-25">"@TempData.Peek("CurrentDrawWinnerName")" has won the draw</p>
        <p class="fs-18">Please Enter Message to be sent to the Winner</p>
        <div class="row nomargin">
            <textarea id="winnerMsg" name="winnerMsg" rows="6" required class="col-xs-12 col-sm-6 fs-20"></textarea>
        </div>
        <div class="clearfix h20"></div>
        <input type="submit" class="fs-20">
    }
</div>

DanoneRewards/Views/Rewards/Create.cshtml
@model DanoneRewards.Models.Reward

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reward</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ConsumerId, "ConsumerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ConsumerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConsumerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DanoneRewards/Views/Rewards/Delete.cshtml
@model DanoneRewards.Models.Reward

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reward</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenerationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenerationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Consumer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consumer.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DanoneRewards/Views/Rewards/Details.cshtml
@model DanoneRewards.Models.Reward

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reward</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenerationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenerationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Consumer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consumer.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RewardId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DanoneRewards/Views/Rewards/Edit.cshtml
@model DanoneRewards.Models.Reward

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reward</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RewardId)

        <div class="form-group">
            @Html.LabelFor(model => model.ConsumerId, "ConsumerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ConsumerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConsumerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenerationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenerationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenerationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DanoneRewards/Views/Rewards/Index.cshtml
@model PagedList.IPagedList<DanoneRewards.Models.Reward>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<div class="whitebg padding-20 fs-20" style="margin-top: -20px;">
    @using (Html.BeginForm("Index", "Rewards", FormMethod.Get))
    {
        <div>
            Search by Name : @Html.TextBox("Name", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
            @Html.ActionLink(" | Export to Excel", "ExportRwardsCsv", "Rewards")
        </div>
        <div class="clearfix h20"></div>
    }
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Name", "Index", new
           {
               SortOrder = ViewBag.NameSortParm,
               Name = TempData.Peek("NameFilter") == null ? "" : TempData.Peek("NameFilter").ToString()
           })
            </th>
            <th>
                @Html.ActionLink("Message", "Index", new
           {
               SortOrder = ViewBag.MessageSortParm,
               Name = TempData.Peek("NameFilter") == null ? "" : TempData.Peek("NameFilter").ToString()
           })
            </th>
            <th>
                @Html.ActionLink("GenerationDate", "Index", new
           {
               SortOrder = ViewBag.GenerationDateSortParm,
               Name = TempData.Peek("NameFilter") == null ? "" : TempData.Peek("NameFilter").ToString()
           })
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Consumer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Message)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GenerationDate)
                </td>
            </tr>
        }

    </table>
    <div class="clearfix h10"></div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount -- Total rewards @TempData["NumberOfRewards"]

    @Html.PagedListPager(Model, page => Url.Action("Index",
            new
            {
                page,
                SortOrder = TempData.Peek("RewardSortOrder") == null ? "" : TempData.Peek("RewardSortOrder").ToString(),
                Name = TempData.Peek("NameFilter") == null ? "" : TempData.Peek("NameFilter").ToString()
            }))
</div>